### ISSUE TITLE
NTR: Concentration of phycocyanin [BODCNVS-2469]

### ISSUE THREAD

**Issue by danibodc** [nvs-vocabs/OG1#8]
Initially requested at https://github.com/OceanGlidersCommunity/OG-format-user-manual/issues/268

Request for a new OG1 term for concentration of phycocyanin. Very similar to the approved term PHYC for phycoerythrin described in https://github.com/OceanGlidersCommunity/OG-format-user-manual/issues/265

Proposed identifier: PHYCOCYANIN
Proposed preferred label: Concentration of phycocyanin per unit volume of the water body [dissolved plus reactive particulate phase] by in-situ fluorometer
Proposed alternative label: phycocyanin_concentration
Proposed definition: Quantity or mass of the specified analyte in a unit volume of an unfiltered sample of fresh or salt water.

**Comment by danibodc** [comment]
To align with existing terms in OG1 I am proposing the following:

Proposed identifier: PHYCOCYANIN
Proposed preferred label: Concentration of phycocyanin by fluorometer
Proposed alternative label: PHYCOCYANIN
Proposed definition: Phycocyanin concentration per unit volume of fresh or salt water.

A new P01 term would need to be created and mapped which would have a preferred label as above:
Concentration of phycocyanin per unit volume of the water body [dissolved plus reactive particulate phase] by in-situ fluorometer.

The P06 units associated with the phycoerythrin parameter are Nanograms per litre - awaiting response from original requester as to whether this is also appropriate for this parameter.

**Comment by danibodc** [comment]
Requester has confirmed units are nanograms per litre

**Comment by gwemon** [comment]
Ah okay, I am glad your are proposing to change the label. I was just going to write: beware that this is trying to look like a P01 code but it isn't following the same conventions... In P01, all concentrations from in situ sensors are "particulate >unknown phase" if the chemical compound of interest is believed to come from particulate material (like e.g. Chla) and "dissolved plus reactive particulate phse" if it is supposed to come from the dissolved phase like e.g. (CDOM, Nitrate, Oxygen). But then we have: https://vocab.nerc.ac.uk/collection/P01/current/PHYCSPP5/ which created a precedent.

**Comment by danibodc** [comment]
Thanks @gwemon I have made a comment on the original ticket about this to let Callum et al know. I will create the new P01 with 'particulate >unknown phase', and we can look to update https://vocab.nerc.ac.uk/collection/P01/current/PHYCSPP5/.

**Comment by danibodc** [comment]
This term has been loaded and will be live on the NVS from tomorrow morning:
PHYCOCYANIN	Concentration of phycocyanin by fluorometer

**Comment by danibodc** [comment]
https://vocab.nerc.ac.uk/collection/OG1/current/PHYCOCYANIN/
